### ISSUE TITLE
Changing "Done" text 

### ISSUE THREAD

**Issue by ghost** [code-troopers/android-betterpickers#109]
How can I change the "Done" text in a CalendarDatePickerDialog?? In a RadialTimePickerDialog there is an method called .setText(String s)! This method is missing in CalendarDatePickerDialog.

**Comment by baer1** [comment]
try to put a this in your strings.xml

<string name="done_label">Fertig</string>

**Comment by zhanghai** [comment]
Hi, it seems that this repo is no longer maintained, since some useful PRs are pending for more than one month without a reply :(

To workaround this issue, maybe, you can try to create a string resource named `done_label` in your own `strings.xml`. Android seems to give priority to the resources in your project over libraries. So generally library projects should have some prefix in its naming.

I noticed this when I defined a color resource named `blue` and found out that it replaced the blue color for BetterPickers. However I forked this repo and switched to gradle, so I'm not sure if this can be reproduced in your project.

If the above method doesn't work, you can try to subclass `CalendarDatePickerDialog` and override `onCreateView`, inside which you use reflection or `findViewById` to set the text for `mDoneButton`.

And finally if you want a clean solution and you don't care much about the trouble, I suggest that you keep your own fork of this project, so you can modify the code freely.

**Comment by CedricGatay** [comment]
The `done_label` in `strings.xml` is the solution. I'm closing this old issue.
