### ISSUE TITLE
Error after adding the library

### ISSUE THREAD

**Issue by samiro** [code-troopers/android-betterpickers#141]
Hello,

I'm trying to use this widget version 1.5.4 and when I try to run Gradle Sync the console shows these errors:

/home/samir/Development/uCity/ucity-project/app/build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.4/res/values/values.xml
Error:(1) Attribute "track" has already been defined
Error:(1) Attribute "thumbTextPadding" has already been defined
Error:(1) Attribute "switchTextAppearance" has already been defined
Error:(1) Attribute "switchMinWidth" has already been defined
Error:(1) Attribute "switchPadding" has already been defined
Error:(1) Attribute "switchStyle" has already been defined

![screenshot from 2015-02-16 17 45 18](https://cloud.githubusercontent.com/assets/2414416/6220374/9e714baa-b603-11e4-9b67-076fbfb1ecc7.png)

Is the same error that https://github.com/derekbrameyer/android-betterpickers/issues/126
How can this be solved?

Thanks!

**Comment by AEFeinstein** [comment]
Seconded. This was not an issue with 1.5.3. samiro, if you change your gradle file to use 1.5.3, it should work.

**Comment by samiro** [comment]
Thanks, it is working. But I need use native Fragment, and this library is using android.support.v4.app.fragment; Any solution?

**Comment by zhanghai** [comment]
@samiro 

You can try [my own fork](https://github.com/DreaminginCodeZH/betterpickers) if you like.

I've already done the code refactoring for using native Fragment (and dropping nineoldandroids, etc, only ics-compatible), and I merged some of the useful PRs. You can checkout the commits.

If you would like to use it, you only need to clone, make values-en strings.xml the default in values (I made zh-CN the default due to my needs), and use gradle to build the library to get the aar. Local repository configuration in gradle file will enable you to integrate local aars into your project.

---

But the last thing to mention is that, you should use SupportFragment. It seems to be Google's recommendation, for example you can getSupportChildFragmentManager() on ICS but not the native one, and the new material design compat only applies to SupportFragment. Support v13 is becoming forgotten.

I made the decision of avoid using support classes when I decided that I won't support 2.x and I want to make my code clean, but now I've found out that I should have been using it.

**Comment by samiro** [comment]
@DreaminginCodeZH 
Thanks. I'll try it.

**Comment by samiro** [comment]
Great! It works.

**Comment by emileb** [comment]
Can someone explain how to get this to work please? I have just update my project to Android Studio so am new to AS. I am getting the same error as the OP, not sure how to integrate for the fork. Thanks!

**Comment by samiro** [comment]
Download the fork (https://github.com/DreaminginCodeZH/betterpickers).
Compile the project with Android Studio and generate .aar file.
Add .aar file to you project.

**Comment by zhanghai** [comment]
@emileb 

For adding the .aar:
1. Copy the genereated `library-release.aar` to your project's module's `aars` directory, rename it to `com.doomonafireball.betterpickers.aar`. (that is to say `./app/aars/com.doomonafireball.betterpickers.aar`)
2. And add the following lines to your module's `build.gradle` (`./app/build.gradle`).

``` gradle
...
repositories {
    flatDir {
        dirs 'aars'
    }
}
...
dependencies {
    ...
    compile (name:'com.doomonafireball.betterpickers', ext:'aar') {
        exclude module: 'support-v4'
    }
    ...
}
```

---

Note that my fork is 4.0+ only, and it uses native Fragment.

**Comment by emileb** [comment]
Ace, that's got it working, thanks guys!

**Comment by samiro** [comment]
@DreaminginCodeZH is posible add Positive and Negative button to CalendarDatePickerDialog?

**Comment by zhanghai** [comment]
@samiro

Well, yes. You can always modify the layout (watch out for multiple layouts for different configurations, such as screen orientation) and add some code.
