### ISSUE TITLE
Possible to Use Better Picker in Main Layout?

### ISSUE THREAD

**Issue by JonathanNakhla** [code-troopers/android-betterpickers#21]
Hi there!

Is it possible to have a Better Picker in the main layout of an activity (such as with the 4.0+ time picker seen here: https://lh3.ggpht.com/LXeEbyIqY2D1f4WD9XAv8JgI_mb6hNWJ3XOjsrpZZIhEzPX2xz7ek9GBCVXWwGC2FaM)?

Thanks,

JN

**Comment by derekbrameyer** [comment]
I'll certainly consider this as a possible feature, but I'm hesitant to do it.  My main concern is that the keyboard view takes up a significant amount of screen real estate.  Inflating the Pickers in a layout would certainly be doable, but it would lead to a lot of screen clutter and the dev would have to do a lot of showing/hiding in order to achieve performant UX.  What are your thoughts?

**Comment by JonathanNakhla** [comment]
Hmm it would be cool to have but definitely not a necessity. The picker is more ideal for a dialog box which is actually what I'm planning on doing now. Thanks for the reply!
