### ISSUE TITLE
improve public api

### ISSUE THREAD

**Issue by Leandros** [code-troopers/android-betterpickers#24]
For example, .setPlusMinusVisibility or .setDecimalVisibilty. 

Just change it to .setPlusMinusVisible(boolean isVisible) or .setDecimalVisible(boolean isVisible).

**Comment by derekbrameyer** [comment]
I'm going to leave it the way it is, because you can set the visibility to `View.GONE` or `View.INVISIBLE` for different behavior.

If you choose to use `View.GONE` for both, the full bottom row becomes tappable by the '0' button.  If, on the other hand, you use `View.INVISIBLE`, only the center button is tappable.
