### ISSUE TITLE
What's wrong with the style? 

### ISSUE THREAD

**Issue by huteri** [code-troopers/android-betterpickers#40]
Hi, I have problem with the style. I'm using light theme, but the result is bad. Can you help me?

![capture](https://f.cloud.github.com/assets/4598788/1233095/d3d12c4a-2908-11e3-8423-f8f14c4201b9.PNG)

**Comment by intrications** [comment]
I would say the problem is that you aren't fully using the light theme but you haven't given enough information to diagnose the cause.

Can you post the part of your code and xml where you set the style?

Have you followed these instructions carefully: https://github.com/derekbrameyer/android-betterpickers#theming?

**Comment by huteri** [comment]
I'm using built in styles from the library.

NumberPickerBuilder npb = new NumberPickerBuilder()
                        .setFragmentManager(getSupportFragmentManager())
                        .setStyleResId(
                                R.style.BetterPickersDialogFragment_Light)
                        .setPlusMinusVisibility(View.INVISIBLE);

npb.show();

**Comment by huteri** [comment]
It seems like I had bad jar build in the library, after I rebuilt the library, it solved.
