### ISSUE TITLE
ExpirationPicker with years earlier than current year

### ISSUE THREAD

**Issue by alopix** [code-troopers/android-betterpickers#99]
I can understand that the expiration picker was designed for real expiration dates e.g. for credit cards.
It still would be nice to use it as a month-year picker only – no matter if in the future or past.

**Comment by alopix** [comment]
Similarly a picker for only past dates would be great.

I already implemented a solution that allows future only or any date. Will create a pull request as soon as past-only works and I have the time :)

**Comment by rocboronat** [comment]
+1

**Comment by szugyi** [comment]
+1 @alopix Any updates?

**Comment by alopix** [comment]
@szugyi sorry, that was at one of my past companies and I didn't manage to actually release the code properly…

**Comment by szugyi** [comment]
@alopix I am thinking about fixing this issue. I have found that the root cause of the issue is this [line](https://github.com/code-troopers/android-betterpickers/blob/5cbd45e2a7e5c3375dae4aa3223f73c6f3188a2c/library/src/main/java/com/codetroopers/betterpickers/expirationpicker/ExpirationPicker.java#L365) preventing the first two digits of the year value to be deleted. Did you find this to be the case too?

**Comment by alopix** [comment]
Does not look like this is still being worked on 🤷🏻‍♂️
